apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167848167
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167848167
    app.kubernetes.io/part-of: test-app-167848167
  name: java-quarkus-167848167
  namespace: bpibhboe-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-167848167
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-167848167
    spec:
      containers:
      - image: quay.io/hacdev/build_service@sha256:8ce7b517f2ce5a91e7d12f5b50c7e2f8128db3463d397089f8fa0bcda71e9d19
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
